# Generated by Django 5.2.7 on 2026-03-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationcode',
            name='created_at',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
