# Generated by Django 5.2.7 on 2026-06-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_subscriptionplan_usersubscription_usagerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='daily_limits',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_limits',
            field=models.BooleanField(default=False, help_text='True = limites mensais (Pro/Pro+), False = limites totais/vitalícios (Free)'),
        ),
    ]
