# Generated by Django 5.2.7 on 2026-05-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind_maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmap',
            name='language',
            field=models.CharField(default='pt', max_length=10),
        ),
    ]
