# Generated by Django 5.2.7 on 2026-05-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind_maps', '0004_mindmap_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmap',
            name='import_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
