# Generated by Django 5.2.7 on 2026-06-07 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind_maps', '0005_mindmap_import_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindmap',
            name='is_shared',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='mindmap',
            index=models.Index(fields=['user', '-created_at'], name='idx_mindmap_user_created'),
        ),
    ]
