services:
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bookar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  backend:
    build: ./backend
    image: backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bookar
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - GENAI_KEY=AIzaSyDyvqvKBMm_ElzlaocaQMGy1UhmsZqHCpU 
      - OLLAMA_KEY=a3a0266acc75406d8255c77af093e451.8tERxykElej3uCmk7itMe2tg
      - SITE_URL=http://localhost:8000
      - DEBUG=True
      - GOOGLE_CLIENT_ID=88572783054-i4pesjt105o1bq83ne3grt9sjss4m616.apps.googleusercontent.com
    depends_on:
      - db
      - redis
  worker:
    image: backend
    command: celery -A core worker -l info
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bookar
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - GENAI_KEY=AIzaSyDyvqvKBMm_ElzlaocaQMGy1UhmsZqHCpU
      - OLLAMA_KEY=74d3ffcd27984f848026dc532370ff74.87ZjfHPN-6kjVml_C_8bC10I
      - GOOGLE_CLIENT_ID=88572783054-i4pesjt105o1bq83ne3grt9sjss4m616.apps.googleusercontent.com
    depends_on:
      - backend
      - redis
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
      AUTH_URL: http://backend:8000/api
      AUTH_SECRET: example-secret
      GOOGLE_CLIENT_ID: 88572783054-i4pesjt105o1bq83ne3grt9sjss4m616.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      NEXTAUTH_URL: http://localhost:3000
      AUTH_TRUST_HOST: 
    depends_on:
      - backend
  flower:
    image: backend
    command: sh -c "celery -A core --broker=redis://redis:6379/0 flower --port=5555"
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  postgres_data: