FROM python:3.12-alpine

WORKDIR /app

RUN apk add --no-cache ffmpeg build-base libffi-dev musl-dev postgresql-dev

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["sh", "-c", "python manage.py migrate --noinput && uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --workers 3"]