# Generated by Django 5.2.7 on 2026-06-07 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explicador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='explicadorroom',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='explicadorroom',
            index=models.Index(fields=['owner', 'is_active', '-created_at'], name='idx_explic_owner_active'),
        ),
    ]
