# Generated by Django 5.2.7 on 2026-05-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind_maps', '0002_mindmap_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmap',
            name='completed_nodes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='quizzes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
