# Generated by Django 5.2.7 on 2026-05-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind_maps', '0003_mindmap_completed_nodes_mindmap_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmap',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
