services:
  worker:
    container_name: "worker"
    image: ${BACKEND_IMAGE}
    env_file: ".env"
    entrypoint: "" 
    command: celery -A core worker -l info
  flower:
    container_name: "flower"
    image: ${BACKEND_IMAGE}
    env_file: ".env"
    entrypoint: "" 
    ports:
      - "5555:5555"
    command: sh -c "celery -A core --broker=${REDIS_URL} flower --address=0.0.0.0 --port=5555 --basic-auth=${FLOWER_USER}:${FLOWER_PASSWORD}"
    depends_on:
      worker:
        condition: service_started
