# Generated by Django 5.2.7 on 2025-10-24 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/videos/')),
                ('duraction', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('watched', models.BooleanField(blank=True, default=False, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='courses/thumbs/')),
                ('level', models.CharField(blank=True, choices=[('I', 'Iniciante'), ('IT', 'Intermediário'), ('A', 'Avançado')], max_length=2, null=True)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modules', models.ManyToManyField(to='courses.module')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.tag')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='videos',
            field=models.ManyToManyField(to='courses.video'),
        ),
    ]
