# Generated by Django 5.2.7 on 2025-12-17 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processando"),
                    ("READY", "Pronto"),
                    ("ERROR", "Erro"),
                ],
                default="PROCESSING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("PROCESSING", "Processando"),
                    ("READY", "Pronto"),
                    ("ERROR", "Erro"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
