# Generated by Django 5.2.7 on 2025-11-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Lesson',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='videos',
            new_name='lesson',
        ),
    ]
