# Generated by Django 5.2.7 on 2025-11-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_video_lesson_rename_videos_module_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='file',
            new_name='video_file',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='key_points',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='scene_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(related_name='modules', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
