# Generated by Django 5.2.7 on 2025-12-23 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_status_course_user_lesson_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="tag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
