# Generated by Django 5.2.7 on 2025-12-23 13:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_tag_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
