# Generated by Django 5.2.7 on 2025-12-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_squashed_0004_remove_course_duration_course_failed_course_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
