# Generated by Django 5.2.7 on 2026-01-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_lesson_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
