# Generated by Django 5.2.7 on 2025-11-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumb',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
