# Generated by Django 5.2.7 on 2026-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_alter_course_thumb_alter_module_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="delivered",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
