# Generated by Django 5.2.7 on 2026-01-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_lesson_delivered"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="deleted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
