# Generated by Django 5.2.7 on 2026-02-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_question_type_quiz_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="max_modules",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
