# Generated by Django 5.2.7 on 2026-02-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_max_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='max_modules',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='module',
        ),
    ]
