# Generated by Django 5.2.7 on 2026-03-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0028_add_module_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulematerial",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
