# Generated by Django 5.2.7 on 2026-06-08 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_choice_is_correct_alter_course_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'created_at'], name='idx_course_featured'),
        ),
    ]
