# Generated by Django 5.2.7 on 2026-06-08 20:22

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models

from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0033_remove_course_idx_course_featured_alter_course_level_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.RemoveIndex(
            model_name="course",
            name="idx_course_title",
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processando"),
                    ("READY", "Pronto"),
                    ("FAILED", "Falhou"),
                    ("CANCELLED", "Cancelado"),
                ],
                default="PROCESSING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name="course",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="course_title_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
