# Generated by Django 5.2.7 on 2026-06-18 06:36

import cloudinary_storage.storage
import django.contrib.auth.models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.accounts.migrations.0018_paymentreceipt_secret_token
# apps.accounts.migrations.0022_backfill_user_subscriptions


def populate_secret_tokens(apps, schema_editor):
    PaymentReceipt = apps.get_model("accounts", "PaymentReceipt")
    for receipt in PaymentReceipt.objects.all():
        receipt.secret_token = uuid.uuid4()
        receipt.save(update_fields=["secret_token"])



    try:
        SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    except LookupError:
        return  # subscriptions app not migrated yet

    User = apps.get_model("accounts", "User")
    UserSubscription = apps.get_model("subscriptions", "UserSubscription")

    free_plan = SubscriptionPlan.objects.filter(slug="free").first()
    if not free_plan:
        return

    for user in User.objects.filter(subscription__isnull=True).iterator():
        UserSubscription.objects.get_or_create(
            user=user,
            defaults={
                "plan": free_plan,
                "status": "active",
            },
        )


class Migration(migrations.Migration):
    replaces = [
        ("accounts", "0001_initial"),
        ("accounts", "0002_user_avatar_user_bio"),
        ("accounts", "0003_alter_user_email_alter_user_username"),
        ("accounts", "0004_emailverificationcode"),
        ("accounts", "0005_waitlist"),
        ("accounts", "0006_alter_user_avatar"),
        ("accounts", "0007_remove_emailverificationcode_created_at_and_more"),
        ("accounts", "0008_remove_user_bio"),
        ("accounts", "0009_alter_emailverificationcode_email"),
        ("accounts", "0010_subscriptionplan_usersubscription_usagerecord"),
        ("accounts", "0011_rename_daily_to_monthly_limits"),
        ("accounts", "0012_subscriptionhistory"),
        ("accounts", "0013_subscriptionplan_kambafy_price_id"),
        ("accounts", "0014_remove_subscriptionplan_kambafy_price_id"),
        ("accounts", "0015_subscriptionplan_kambafy_price_id"),
        ("accounts", "0016_subscriptionplan_manual_payment_account_name_and_more"),
        ("accounts", "0017_notification"),
        ("accounts", "0018_paymentreceipt_secret_token"),
        ("accounts", "0019_add_phone_fields"),
        ("accounts", "0020_remove_moved_models"),
        ("accounts", "0021_remove_waitlist"),
    ]

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to="avatars/",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("code", models.CharField(max_length=6)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "max_explicador_messages",
                    models.IntegerField(
                        blank=True, help_text="None = ilimitado", null=True
                    ),
                ),
                (
                    "max_explicador_participants",
                    models.IntegerField(blank=True, null=True),
                ),
                ("max_courses_generated", models.IntegerField(blank=True, null=True)),
                ("max_mindmaps_generated", models.IntegerField(blank=True, null=True)),
                ("max_mindmap_modules", models.IntegerField(blank=True, null=True)),
                ("max_mindmap_quizzes", models.IntegerField(blank=True, null=True)),
                ("max_mindmap_materials", models.IntegerField(blank=True, null=True)),
                (
                    "gateway_price_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "monthly_limits",
                    models.BooleanField(
                        default=False,
                        help_text="True = limites mensais (Pro/Pro+), False = limites totais/vitalícios (Free)",
                    ),
                ),
                (
                    "kambafy_price_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "manual_payment_account_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "manual_payment_iban",
                    models.CharField(blank=True, default="", max_length=50),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("canceled", "Cancelado"),
                            ("past_due", "Vencido"),
                            ("expired", "Expirado"),
                            ("trialing", "Em teste"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField(auto_now_add=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_gateway",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "gateway_subscription_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("gateway_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="accounts.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("explicador_message", "Mensagem no Explicador"),
                            ("course_generated", "Curso Gerado"),
                            ("mindmap_generated", "Mapa Mental Gerado"),
                        ],
                        max_length=50,
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date", "metric")},
            },
        ),
        migrations.CreateModel(
            name="SubscriptionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                (
                    "payment_gateway",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "subscription histories",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True, default="")),
                ("type", models.CharField(default="info", max_length=50)),
                ("link", models.CharField(blank=True, default="", max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt",
                    models.ImageField(
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to="receipts/",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("iban", models.CharField(blank=True, default="", max_length=50)),
                (
                    "account_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("rejected", "Recusado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="accounts.subscriptionplan",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("secret_token", models.UUIDField(editable=False, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(
            code=populate_secret_tokens,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="paymentreceipt",
            name="secret_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="manual_payment_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="paymentreceipt",
                    name="plan",
                ),
                migrations.RemoveField(
                    model_name="paymentreceipt",
                    name="reviewed_by",
                ),
                migrations.RemoveField(
                    model_name="paymentreceipt",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="subscriptionhistory",
                    name="plan",
                ),
                migrations.RemoveField(
                    model_name="subscriptionhistory",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="usersubscription",
                    name="plan",
                ),
                migrations.AlterUniqueTogether(
                    name="usagerecord",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="usagerecord",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="usersubscription",
                    name="user",
                ),
                migrations.DeleteModel(
                    name="Notification",
                ),
                migrations.DeleteModel(
                    name="PaymentReceipt",
                ),
                migrations.DeleteModel(
                    name="SubscriptionHistory",
                ),
                migrations.DeleteModel(
                    name="SubscriptionPlan",
                ),
                migrations.DeleteModel(
                    name="UsageRecord",
                ),
                migrations.DeleteModel(
                    name="UserSubscription",
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Waitlist",
        ),
    ]
