# Generated by Django 5.2.7 on 2026-06-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
