# Generated by Django 5.2.7 on 2026-06-13 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_emailverificationcode_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('daily_limits', models.BooleanField(default=False, help_text='True = limites diários (Pro/Pro+), False = limites totais (Free)')),
                ('max_explicador_messages', models.IntegerField(blank=True, help_text='None = ilimitado', null=True)),
                ('max_explicador_participants', models.IntegerField(blank=True, null=True)),
                ('max_courses_generated', models.IntegerField(blank=True, null=True)),
                ('max_mindmaps_generated', models.IntegerField(blank=True, null=True)),
                ('max_mindmap_modules', models.IntegerField(blank=True, null=True)),
                ('max_mindmap_quizzes', models.IntegerField(blank=True, null=True)),
                ('max_mindmap_materials', models.IntegerField(blank=True, null=True)),
                ('gateway_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('canceled', 'Cancelado'), ('past_due', 'Vencido'), ('expired', 'Expirado'), ('trialing', 'Em teste')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField(auto_now_add=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('payment_gateway', models.CharField(blank=True, default='', max_length=20)),
                ('gateway_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('gateway_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='accounts.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('metric', models.CharField(choices=[('explicador_message', 'Mensagem no Explicador'), ('course_generated', 'Curso Gerado'), ('mindmap_generated', 'Mapa Mental Gerado')], max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'metric')},
            },
        ),
    ]
