# Generated by Django 5.2.7 on 2026-06-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_subscriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='kambafy_price_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
