# Generated by Django 5.2.7 on 2026-06-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_subscriptionplan_kambafy_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='kambafy_price_id',
        ),
    ]
