# Generated by Django 5.2.7 on 2026-06-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_subscriptionplan_kambafy_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='kambafy_price_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
