# Generated by Django 5.2.7 on 2026-06-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_paymentreceipt_secret_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='manual_payment_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
