# Generated by Django 5.2.7 on 2026-06-18 06:36

import apps.courses.models
import cloudinary_storage.storage
import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('courses', '0001_initial'), ('courses', '0002_lesson_delivered'), ('courses', '0003_coursegenerationcontext'), ('courses', '0004_question_remove_course_failed_alter_course_status_and_more'), ('courses', '0005_remove_lesson_delivered'), ('courses', '0006_alter_course_thumb_alter_module_name'), ('courses', '0007_lesson_delivered'), ('courses', '0008_course_deleted'), ('courses', '0009_question_type_quiz_module'), ('courses', '0010_course_max_modules'), ('courses', '0011_remove_course_max_modules_remove_question_type_and_more'), ('courses', '0012_course_max_modules'), ('courses', '0013_quiz_module'), ('courses', '0014_module_status'), ('courses', '0015_course_certificate_file_course_certificate_status'), ('courses', '0016_alter_course_certificate_file_alter_course_thumb_and_more'), ('courses', '0017_alter_course_certificate_file_alter_course_status_and_more'), ('courses', '0018_alter_course_thumb'), ('courses', '0019_remove_lesson_watched_courseenrollment_and_more'), ('courses', '0020_remove_course_certificate_file_and_more'), ('courses', '0021_remove_course_user'), ('courses', '0022_alter_courseenrollment_certificate_file_courseshare_and_more'), ('courses', '0023_course_uuid_lesson_short_id_module_uuid'), ('courses', '0024_alter_course_uuid_alter_lesson_short_id_and_more'), ('courses', '0025_quiz_uuid'), ('courses', '0026_choice_uuid_question_uuid'), ('courses', '0027_course_owner'), ('courses', '0028_add_module_material'), ('courses', '0029_modulematerial_content'), ('courses', '0030_lesson_segments_data_alter_lesson_status'), ('courses', '0031_alter_choice_is_correct_alter_course_level_and_more'), ('courses', '0032_add_course_indexes'), ('courses', '0033_remove_course_idx_course_featured_alter_course_level_and_more'), ('courses', '0034_remove_course_idx_course_title_alter_course_status_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('B', 'Beginner'), ('IT', 'Intermediate'), ('A', 'Advance')], db_index=True, max_length=2, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processando'), ('READY', 'Pronto'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelado')], db_index=True, default='PROCESSING', max_length=20)),
                ('thumb', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='courses/thumbs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_modules', models.PositiveIntegerField(blank=True, default=5, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
                ('status', models.CharField(choices=[('PROCESSING', 'Processando'), ('READY', 'Pronto'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelado')], default='READY', max_length=20)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('duration', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PLANNING', 'Planeando Conteúdo'), ('GENERATING_MEDIA', 'Gerando Vídeo'), ('PROCESSING', 'Processando'), ('READY', 'Pronto'), ('ERROR', 'Erro'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=20)),
                ('lesson_file', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='courses/lessons/')),
                ('narration', models.TextField(blank=True, null=True)),
                ('key_points', models.CharField(blank=True, max_length=150, null=True)),
                ('scene_suggestion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module')),
                ('delivered', models.BooleanField(blank=True, db_index=True, default=False, null=True)),
                ('short_id', models.CharField(default=apps.courses.models.generate_short_id, max_length=12, unique=True)),
                ('segments_data', models.JSONField(blank=True, help_text='Cache do guião gerado pela Task 1', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseGenerationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField()),
                ('prompt', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('current_module_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_context', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course')),
                ('lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson')),
                ('module', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.module')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer', null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='CourseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='courses.course')),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseShareClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_shares', to=settings.AUTH_USER_MODEL)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='courses.courseshare')),
            ],
            options={
                'unique_together': {('share', 'recipient')},
            },
        ),
        migrations.CreateModel(
            name='ModuleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='courses/materials/')),
                ('status', models.CharField(choices=[('PROCESSING', 'Processando'), ('READY', 'Pronto'), ('FAILED', 'Falhou')], default='PROCESSING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='courses.module')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.question')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('passed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('PAUSED', 'Pausado'), ('FINISHED', 'Concluído')], default='ACTIVE', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('certificate_file', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='courses/certificates/')),
                ('certificate_status', models.CharField(choices=[('NOT_GENERATED', 'Não Gerado'), ('PROCESSING', 'Processando'), ('READY', 'Pronto')], default='NOT_GENERATED', max_length=20)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'unique_together': {('course', 'user')},
                'indexes': [models.Index(fields=['user', 'deleted'], name='idx_enrollment_user_deleted'), models.Index(fields=['course', 'user', 'deleted'], name='idx_enrollment_course_user_del')],
            },
        ),
        migrations.AddIndex(
            model_name='courseshare',
            index=models.Index(fields=['course', 'sharer'], name='idx_courseshare_course_sharer'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'created_at'], name='idx_module_course_created'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'user', 'passed'], name='idx_quizattempt_quiz_user_pass'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', '-completed_at'], name='idx_quizattempt_quiz_completed'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('B', 'Beginner'), ('IT', 'Intermediate'), ('A', 'Advance')], max_length=2, null=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='idx_course_status'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='idx_course_title'),
        ),
        django.contrib.postgres.operations.TrigramExtension(
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='idx_course_title',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processando'), ('READY', 'Pronto'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelado')], default='PROCESSING', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='course_title_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
