# Generated by Django 5.2.7 on 2026-01-08 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_lesson_delivered"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseGenerationContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_prompt", models.TextField()),
                ("prompt", models.TextField(blank=True, null=True)),
                ("response", models.TextField(blank=True, null=True)),
                ("current_module_index", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_context",
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
