# Generated by Django 5.2.7 on 2026-02-15 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_course_max_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="module",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz",
                to="courses.module",
            ),
        ),
    ]
