# Generated by Django 5.2.7 on 2026-03-18 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0020_remove_course_certificate_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="user",
        ),
    ]
