# Generated by Django 5.2.7 on 2026-03-20 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_course_uuid_alter_lesson_short_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
