# Generated by Django 5.2.7 on 2026-06-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_squashed_0034_remove_course_idx_course_title_alter_course_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('B', 'Beginner'), ('IT', 'Intermediate'), ('A', 'Advance')], db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='coursegenerationcontext',
            name='prompt',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
