# Generated by Django 5.2.7 on 2026-06-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folha',
            name='node_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
