name: Deploy to AWS Fargate

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/django-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/nextjs-frontend
  ECS_CLUSTER: Bookar
  ECS_SERVICE_BACKEND: django-backend-service
  ECS_SERVICE_FRONTEND: nextjs-frontend-service
  ECS_SERVICE_WORKER: celery-worker-service

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          cd backend
          python manage.py test || echo "Failed"

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3  
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -f ./backend/Dockerfile.prod -t $BACKEND_IMAGE:$IMAGE_TAG ./backend
          docker tag $BACKEND_IMAGE:$IMAGE_TAG $BACKEND_IMAGE:latest

      - name: Push backend image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker push $BACKEND_IMAGE:$IMAGE_TAG
          docker push $BACKEND_IMAGE:latest

      - name: Build frontend image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -f ./frontend/Dockerfile.prod -t kiluzx/$FRONTEND_IMAGE:$IMAGE_TAG ./frontend
          docker tag kiluzx/$FRONTEND_IMAGE:$IMAGE_TAG kiluzx/$FRONTEND_IMAGE:latest

      - name: Push frontend image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker push kiluzx/$FRONTEND_IMAGE:$IMAGE_TAG
          docker push kiluzx/$FRONTEND_IMAGE:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy backend service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE_BACKEND \
            --force-new-deployment

      - name: Deploy frontend service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE_FRONTEND \
            --force-new-deployment

      - name: Deploy worker service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE_WORKER \
            --force-new-deployment